"""init

Revision ID: 1ca725ea1623
Revises: b82a5074f634
Create Date: 2023-10-27 15:47:05.691998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ca725ea1623'
down_revision = 'b82a5074f634'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
